version: '3.3'

services:
  frontend:
    image: givoka/ecommerce-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development


  backend:
    image: givoka/ecommerce-backend:latest
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb+srv://taquocitali:taquocitali@cluster0.a6vysmx.mongodb.net/ecomerce_project?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=myjwtsecret
      - JWT_REFRESH_SECRET=myjwtrefreshsecret
      - FRONTEND_URL=http://localhost:3000