name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      # Đăng nhập Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build và đẩy backend image
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-backend:latest

      # Build và đẩy frontend image
      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-frontend:latest

      # (Tùy chọn) Chạy test
      - name: Run tests for Backend
        run: |
          cd backend
          npm install
          npm test
        if: success()

      - name: Run tests for Frontend
        run: |
          cd frontend
          npm install
          npm test
        if: success()